# Generated by Django 3.0.2 on 2020-01-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Accomplishment',
                'verbose_name_plural': 'Accomplishment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('mail', models.EmailField(max_length=254, verbose_name='Direccion de correo')),
                ('linkedIn', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['phone'],
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Degree')),
            ],
            options={
                'verbose_name': 'Degree',
                'verbose_name_plural': 'Degrees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('birth', models.DateField(verbose_name='Birth')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
            ],
            options={
                'verbose_name': 'GeneralInfo',
                'verbose_name_plural': 'GeneralInfo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about', models.CharField(max_length=300, verbose_name='About')),
                ('intro', models.TextField()),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Introduction',
                'verbose_name_plural': 'Instroductions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('percent', models.CharField(max_length=4, verbose_name='Percent')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('percent', models.CharField(max_length=4, verbose_name='Percent')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'SoftSkill',
                'verbose_name_plural': 'SoftSkills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=300, verbose_name='Job')),
                ('place', models.CharField(max_length=300, verbose_name='Place')),
                ('zone', models.CharField(max_length=300, verbose_name='Zone')),
                ('resume', models.TextField()),
                ('startdate', models.DateField(verbose_name='Fecha de inicio')),
                ('enddate', models.DateField(verbose_name='Fecha de termino')),
                ('accomplish', models.ManyToManyField(to='usuario.Accomplishments')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['job'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=200, verbose_name='Place')),
                ('area', models.CharField(max_length=200, verbose_name='Major')),
                ('special', models.CharField(max_length=200, verbose_name='Major')),
                ('startdate', models.DateField(verbose_name='Fecha de inicio')),
                ('enddate', models.DateField(verbose_name='Fecha de termino')),
                ('degree', models.ManyToManyField(to='usuario.Degree')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['place'],
            },
        ),
    ]
