# Generated by Django 3.0.2 on 2020-01-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='me',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
