# Generated by Django 3.0.2 on 2020-01-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_generalinfo_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='special',
            field=models.CharField(max_length=200, verbose_name='Speciality'),
        ),
    ]
