# Generated by Django 3.0.2 on 2020-01-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200109_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='enddate',
            field=models.DateField(null=True, verbose_name='Fecha de termino'),
        ),
    ]
