# Generated by Django 3.0.2 on 2020-01-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200109_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de termino'),
        ),
    ]
