# Generated by Django 3.0.2 on 2020-01-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20200109_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='me',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
