# Generated by Django 3.0.2 on 2020-01-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20200109_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introduction',
            options={'ordering': ['id'], 'verbose_name': 'Introduction', 'verbose_name_plural': 'Introductions'},
        ),
    ]
