# Generated by Django 3.0.2 on 2020-01-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20200109_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.Degree'),
        ),
    ]
